name: Build and deploy ASP.Net Core app to Azure Web App - MenuBuilderBack

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x' # Certifique-se que seu projeto já suporta .NET 10 (Preview/RC)

      - name: Restore dependencies
        run: dotnet restore


      - name: Localizar Arquivos de Projeto
        run: Get-ChildItem -Recurse -Filter *.csproj | Select-Object FullName

      - name: dotnet publish
        # Ajustei o output para ./publish (pasta local no runner)
        run: dotnet publish MenuBuilderBack/MenuBuilderBack.csproj -c Release -r win-x64 --self-contained true -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish # Deve ser o mesmo caminho do output acima

  deploy:
    runs-on: windows-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./myapp # Recomendo baixar em uma subpasta para evitar conflitos
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MenuBuilderBack'
          slot-name: 'Production'
          package: ./myapp # Aponta para a pasta onde você baixou o artefato
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7A35A174F9F1491B95F0A1B7EFC79279 }}